PREFIX : <http://www.mysparql.com/resource/northwind/>

# Customers who bought product-61

SELECT DISTINCT # eliminates duplicates in case the same customer bought a product more than once
  ?customer 
  ?companyName 
  ?contactName
WHERE { 
  GRAPH :dataGraph {
    ?orderDetail :hasProduct :product-61 ; 
                 :belongsToOrder ?order .
    ?order       :hasCustomer ?customer .
    ?customer	 :companyName ?companyName ;
                 :contactName ?contactName .
  }
}
ORDER BY ?customer




# The following is the property path version of the query above
PREFIX : <http://www.mysparql.com/resource/northwind/>
SELECT DISTINCT ?customer 
WHERE { GRAPH ?graph {
    ?customer ^:hasCustomer/^:belongsToOrder/:hasProduct :product-61 .
  }
}
ORDER BY ?product

