PREFIX        : <http://www.mysparql.com/resource/northwind/>
PREFIX kggraph: <http://www.mysparql.com/resource/northwind/graph/>

# Customers who bought product-61

SELECT DISTINCT # eliminates duplicates in case the same customer bought a product more than once
  ?customer 
  ?companyName 
  ?contactName
WHERE { 
  GRAPH kggraph:dataGraph {
    ?customer    a :Customer ;
                 :companyName ?companyName ;
                 :contactName ?contactName .
    ?order       a :Order ;
                 :hasCustomer ?customer .
    ?orderDetail a :OrderDetail ;
                 :hasProduct :product-61 ;
                 :belongsToOrder ?order .
  }
}
ORDER BY ?customer


# The following is the property path version of the query above

PREFIX        : <http://www.mysparql.com/resource/northwind/>
PREFIX kggraph: <http://www.mysparql.com/resource/northwind/graph/>

SELECT DISTINCT
    ?customer
WHERE {
    GRAPH ?graph {
        ?customer ^:hasCustomer/^:belongsToOrder/:hasProduct :product-61 .
    }
}
ORDER BY ?customer



