PREFIX        : <http://www.mysparql.com/resource/northwind/>
PREFIX kggraph: <http://www.mysparql.com/resource/northwind/graph/>

# Customers who bought product-61

# The rule ":boughtProduct" only tells if a customer bought product-61, but not how many times.
# Therefore, the DISTINCT is not required to eliminate duplicates. 
SELECT 
  ?customer 
  ?companyName 
  ?contactName
WHERE { 
  GRAPH kggraph:dataGraph {
    ?customer a :Customer ;
              :boughtProduct :product-61 ;
              :companyName ?companyName ;
              :contactName ?contactName .
  }
}
ORDER BY ?customer