PREFIX     : <http://www.mysparql.com/resource/northwind/>
PREFIX kggraph: <http://www.mysparql.com/resource/northwind/graph/>

# Products bought by the same customer
# Returns all combinations of product-2 and product-61 bought by a customer across all orders.

SELECT 
    (COUNT (1) AS ?Count) 
    ?graph
WHERE {
    GRAPH ?graph {
        :product-2 ^:hasProduct/:belongsToOrder/:hasCustomer/^(^:hasProduct/:belongsToOrder/:hasCustomer) :product-61
    }
}