PREFIX        : <http://www.mysparql.com/resource/northwind/>
PREFIX kggraph: <http://www.mysparql.com/resource/northwind/graph/>

# Top 5 customers by product count

SELECT 
  ?customer 
  ?companyName 
  ?contactName
  ?productCount
WHERE { 
  GRAPH kggraph:dataGraph {
    ?customer :hasProductCount ?productCount ;
              :companyName ?companyName ;
              :contactName ?contactName .
  }
}
ORDER BY DESC(?productCount)
LIMIT 5