PREFIX        : <http://www.mysparql.com/resource/northwind/>
PREFIX kggraph: <http://www.mysparql.com/resource/northwind/graph/>

# Customers who never placed an order

SELECT DISTINCT 
  ?customer
  ?companyName
  ?postalCode
  ?city
  ?country
WHERE { 
    GRAPH ?graph {
        ?customer a :CustomerWithoutOrder ;
                    :customerID ?customerID ;
                    :companyName ?companyName ;
                    :city ?city ;
                    :country ?country .
        OPTIONAL {?customer :postalCode ?postalCode} .
    }
}
ORDER BY ?customer