PREFIX        : <http://www.mysparql.com/resource/northwind/>
PREFIX kggraph: <http://www.mysparql.com/resource/northwind/graph/>

# Add an order to a customer who had never placed an order before

INSERT DATA {
    GRAPH kggraph:dataGraph {
        :order-99999 a :Order ;
                     :hasCustomer :customer-FISSA .
        :orderDetail-99999-61 a :OrderDetail ;
                              :hasProduct :product-61 ;
                              :belongsToOrder :order-99999 .
    }
}