PREFIX     : <http://www.mysparql.com/resource/northwind/>

# Products bought by the same customer 

SELECT 
    (COUNT (1) AS ?Count) 
    ?graph
WHERE {
    GRAPH ?graph {
        :product-2 ^:hasProduct/:belongsToOrder/:hasCustomer/^(^:hasProduct/:belongsToOrder/:hasCustomer) :product-61
    }
}