PREFIX     : <http://www.mysparql.com/resource/northwind/>

# The rule answers if a customer bought product-61, but not how many times.
# Therefore, the DISTINCT is not needed in this query anymore. 
# TODO: create a rule to include how many times a customer bought a product. 
SELECT 
  ?customer 
  ?companyName 
  ?contactName
WHERE { 
  GRAPH :dataGraph {
    ?customer :boughtProduct :product-61 ;
              :companyName ?companyName ;
              :contactName ?contactName .
  }
}
ORDER BY ?customer




# The following is the property path version of the query above

SELECT DISTINCT ?customer 
WHERE { GRAPH ?graph {
    :product-61 ^:boughtProduct ?customer .
  }
}
ORDER BY ?product
