PREFIX     : <http://www.mysparql.com/resource/northwind/>

SELECT DISTINCT 
  ?customer 
  ?companyName 
  ?contactName
WHERE { 
  GRAPH :dataGraph {
    ?orderDetail :hasProduct :product-61 ; 
                 :belongsToOrder ?order .
    ?order       :hasCustomer ?customer .
    ?customer	   :companyName ?companyName ;
                 :contactName ?contactName .
  }
}
ORDER BY ?customer
