PREFIX     : <http://www.mysparql.com/resource/northwind/>

SELECT # The rule already did the DISTINCT for you.
  ?customer 
  ?companyName 
  ?contactName
WHERE { 
  GRAPH :dataGraph {
    ?customer :boughtProduct :product-61 ;
              :companyName ?companyName ;
              :contactName ?contactName .
  }
}
ORDER BY ?customer