PREFIX     : <http://www.mysparql.com/resource/northwind/>

# WARNING!!! Must be careful here. This query won't produce the expected result becuase 
# the rule doesn't account for customers that bought the same product many times.
SELECT 
    (COUNT (1) AS ?Count) 
    ?graph
WHERE {
    GRAPH ?graph {
        :product-2 ^:boughtProduct/^(^:boughtProduct) :product-61
    }
}